apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 10
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress                           # wordpress:php7.1-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "fs-db.cg06yq18bl4w.ap-south-1.rds.amazonaws.com"
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-credentials
              key: username
        - name: WORDPRESS_DB_PASSWORD
          #value: "VzIjPu2wjtxN6ur7"
          valueFrom:
            secretKeyRef:
              name: wordpress-db-credentials
              key: password
        - name: WORDPRESS_DB_NAME
          value: "wordpressdb"

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

