apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-credentials
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded "admin"
  password: VnpJalB1MndqdHhONnVyNw==  # base64 encoded "VzIjPu2wjtxN6ur7"

